.PHONY: all demo challenge clean

all: demo challenge

demo:
	$(MAKE) -C demo

challenge:
	$(MAKE) -C challenge_src

clean:
	$(MAKE) -C demo clean
	$(MAKE) -C challenge_src clean

.PHONY: all demo challenge clean
